{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   KeyError: 'user_id'\n", "test_name": "test_TC03_Invalid_Endpoint", "rerun": "0"}}, "suite_name": "tests/Test_Second_TestCase.py"}}}, "date": "February 01, 2025", "start_time": 1738361296.208281, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}