{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 2}, "tests": {"0": {"status": "ERROR", "message": "pytestconfig = <_pytest.config.Config object at 0x000001468EBDE270>\n\n    @pytest.fixture(scope=\"session\")\n    def config(pytestconfig):\n        \"\"\"Loads the selected environment's configuration from config.json\"\"\"\n        env = pytestconfig.getoption(\"--env\") or \"qa\"\n>       with open(\"config/config.json\", \"r\") as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'\n\ntests\\conftest.py:14: FileNotFoundError\n", "test_name": "test_TC01_Health_Check", "rerun": "0"}, "1": {"status": "ERROR", "message": "pytestconfig = <_pytest.config.Config object at 0x000001468EBDE270>\n\n    @pytest.fixture(scope=\"session\")\n    def config(pytestconfig):\n        \"\"\"Loads the selected environment's configuration from config.json\"\"\"\n        env = pytestconfig.getoption(\"--env\") or \"qa\"\n>       with open(\"config/config.json\", \"r\") as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'\n\ntests\\conftest.py:14: FileNotFoundError\n", "test_name": "test_TC03_Invalid_Endpoint", "rerun": "0"}}, "suite_name": "tests/Test_First_TestCase.py"}}}, "date": "February 01, 2025", "start_time": 1738322453.8123958, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "2", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}