{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 4, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://reqres.in/api/uat/health\n       RuntimeError: GET request failed: 404 Client Error: Not Found for url: https://reqres.in/api/uat/health\n", "test_name": "test_TC01_Health_Check", "rerun": "0"}, "1": {"status": "FAIL", "message": "   AssertionError: Login failed\n   assert 201 == 200\n    +  where 201 = <Response [201]>.status_code\n", "test_name": "test_TC02_Login", "rerun": "0"}, "2": {"status": "FAIL", "message": "       requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://reqres.in/api/uat/users/1\n       RuntimeError: GET request failed: 404 Client Error: Not Found for url: https://reqres.in/api/uat/users/1\n", "test_name": "test_TC03_Get_User_Details", "rerun": "0"}, "3": {"status": "FAIL", "message": "       requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://reqres.in/api/uat/invalid_endpoint\n       RuntimeError: GET request failed: 404 Client Error: Not Found for url: https://reqres.in/api/uat/invalid_endpoint\n", "test_name": "test_TC04_Invalid_Endpoint", "rerun": "0"}}, "suite_name": "tests/Test_First_TestCase.py"}}}, "date": "January 31, 2025", "start_time": 1738307670.6736279, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "4", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "4"}